# =============================================================
# Country Configuration and Column Mapping
# Purpose:
#  - Locate raw country files
#  - Map raw column names to standardized schema
#  - Define metadata and processing rules
# =============================================================

tanzania:
  raw_file: data/raw/tanzania/hf_tanzania_2026.csv
  facility_name_column:  name
  facility_code_column: facility_code
  admin1_column: region
  facility_type: facilitytypegroup
  facility_ownership: ownershipgroup
  latitude: latitude
  longitude: longitude
  operation_status: operatingstatus

malawi:
  raw_file: data/raw/malawi/MHFR_Facilities.xlsx
  facility_name_column: COMMON NAME
  facility_code_column: CODE
  admin1_column: ZONE
  facility_type: TYPE
  facility_ownership: OWNERSHIP
  latitude: LATITUDE
  longitude: LONGITUDE
  operation_status: STATUS  

uganda:
  raw_file: data/raw/uganda/hf_data_extracted.csv
  facility_name_column: short_name
  facility_code_column: mfl_uid
  admin1_column: region
  facility_type: level
  facility_ownership: ownership
  latitude: latitude
  longitude: longitude
  operation_status: status

zambia:
  raw_file: data/raw/zambia/mfl_facilities_export20260208091829.xlsx
  facility_name_column: Name
  facility_code_column: MFL_Code
  admin1_column: Province
  facility_type: Type
  facility_ownership: Ownership
  latitude: Latitude
  longitude: Longitude
  operation_status: Operational_status

nigeria:
  raw_file: data/raw/nigeria/GRID3_NGA_health_facilities_v2_0_5806009649412052847 (1).csv
  facility_name_column: facility_name
  facility_code_column: nhfr_facility_code
  admin1_column: state
  facility_type: facility_level
  facility_ownership: ownership
  latitude: latitude
  longitude: longitude
  #operation_status:

